# -- setting

# set Default tmux shell
set -g default-shell $SHELL
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',*:RGB'

setw -g xterm-keys on
set -s focus-events on

# disable Ctrl + b Prefix
unbind C-b
# Set Ctrl + a  for Prefix
set -g prefix C-a
bind C-a send-prefix


# rename title
set -g set-titles on
set -g set-titles-string '#h ❐ #S ● #I #W'
setw -g automatic-rename on
set -g renumber-windows on

# status
set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on

#set-option -g status-position top
set -sg repeat-time 600

# Removes ESC delay (important for Neovim)
set -s escape-time 10

# key-mode -> vi
setw -g mode-keys vi

# set index
set -g base-index 1
# set pane index
set -g pane-base-index 1

# Use X to close windows
unbind &
bind X killw
# set r for reload config
bind r source-file ~/.tmux.conf \;  display-message "Config reloaded.."
# set ctrl l to clear history
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history


# copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel


# sync pane mode 建立同步視窗快捷鍵
bind  C-b setw synchronize-panes

# mouse
set -g mouse on

# activity
set -g monitor-activity on

# listen to alerts from all windows
set-option -g bell-action any

# set history up to 100000
set -g history-limit 100000


# tpm - tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'catppuccin/tmux'

#---------------
# tmux-fzf
set -g @plugin 'sainnhe/tmux-fzf'
TMUX_FZF_LAUNCH_KEY="C-f"
TMUX_FZF_PANE_FORMAT="[#{window_name}] #{pane_current_command}  [#{pane_width}x#{pane_height}] [history #{history_size}/#{history_limit}, #{history_bytes} bytes] #{?pane_active,[active],[inactive]}"
#--------------

#---------------
# tmux-plugins/tmux-prefix-highlight
set -g @prefix_highlight_fg 'white' # default is 'colour231'
set -g @prefix_highlight_bg 'blue'  # default is 'colour04'
set -g @prefix_highlight_show_copy_mode 'on'

# --------------
set -g @catppuccin_flavour 'mocha' # or frappe, macchiato, mocha

# tmux-resurrect + tmux-continuum
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# always on the button
run '~/.tmux/plugins/tpm/tpm'
