-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- This file is automatically loaded by lazyvim.config.init
-- local Util = require("lazyvim.util")

-- DO NOT USE THIS IN YOU OWN CONFIG!!
-- use `vim.keymap.set` instead
-- local map = Util.safe_keymap_set
-- local opts = { noremap = true, silent = true }
--
--
--
-- Split window
-- map("n", "ss", ":split<Return>", opts)
-- map("n", "sv", ":vsplit<Return>", opts)
-- Move window
-- map("n", "sh", "<C-w>h", opts)
-- map("n", "sk", "<C-w>k", opts)
-- map("n", "sj", "<C-w>j", opts)
-- map("n", "sl", "<C-w>l", opts)
